name: NetworkManager
version: '${version}'
main: dev.rgbmc.network.NetworkManager
api-version: 1.13
authors: [ FlyProject ]
description: A utility for managing external network traffic to your Minecraft server
commands:
  networkmanager:
    permission: networkmanager.admin
    aliases:
      - nman
      - netman
      - nmanager
      - network
      - netmanager
      - nm
permissions:
  networkmanager.admin:
    default: op
